options:
  max-time: 10
pipelines:
  default:
    - parallel: &build_steps
      - step:
          name: Build FunApp
          image: node:lts
          size: 2x
          caches:
            - yarn
          script:
            - git submodule update --init
            - ./build.sh
          artifacts:
            - dist/**
      - step:
          name: Lint FunApp
          image: node:lts
          caches:
            - yarn
          script:
            - git submodule update --init
            - ./lint.sh
  pull-requests:
    '**':
      - parallel: *build_steps
  branches:
    master:
      - parallel: *build_steps
      - step:
          name: Upload
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            # Workaround for pipes not supporting private docker repos.
            - docker pull myprocessx/upload-artifact
            - pipe: ozma-io/upload-artifact:master
              variables:
                LOCAL_PATH: dist
          artifacts:
            - artifact.json
      - step:
          name: Deploy to test
          deployment: test
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          caches:
            - docker
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - docker pull myprocessx/deploy-artifact
            - pipe: ozma-io/deploy-artifact:master

definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn
