options:
  max-time: 10
pipelines:
  default:
    - parallel: &build_steps
      - step:
          name: Build FunApp
          image: node:lts
          size: 2x
          caches:
            - yarn
          script:
            - git submodule update --init
            - ./build.sh
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - pipe: ozma/upload-artifact:master
              variables:
                LOCAL_PATH: dist
          artifacts:
            - artifact.json
      - step:
          name: Lint FunApp
          image: node:lts
          caches:
            - yarn
          script:
            - git submodule update --init
            - ./lint.sh

  pull-requests:
    '**':
      - parallel: *build_steps
  branches:
    master:
      - parallel: *build_steps
      - step:
          name: Deploy to test
          deployment: test
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - pipe: ozma/deploy-artifact:master
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - pipe: ozma/deploy-artifact:master

definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn
