options:
  max-time: 10
pipelines:
  default:
    - parallel: &build_steps
      - step:
          name: Build FunApp
          image: node:lts
          size: 2x
          caches:
            - yarn
          script:
            - git submodule update --init
            # - ./build.sh
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            # Pipes from private repositories are currently not supported:
            # https://jira.atlassian.com/browse/BCLOUD-18270
            # - pipe: ozma-io/upload-artifact:master
            - pipe: docker://myprocessx/upload-artifact:latest
              variables:
                LOCAL_PATH: dist
                AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
                AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
          artifacts:
            - artifact.json
      - step:
          name: Lint FunApp
          image: node:lts
          caches:
            - yarn
          script:
            - git submodule update --init
            # - ./lint.sh

  pull-requests:
    '**':
      - parallel: *build_steps
  branches:
    master:
      - parallel: *build_steps
      - step:
          name: Deploy to test
          deployment: test
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - pipe: ozma-io/deploy-artifact:master
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            - pipe: ozma-io/deploy-artifact:master

definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn
