services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    environment:
      POSTGRES_PASSWORD: postgres
    shm_size: 4gb

  keycloak:
    build:
      context: .
      dockerfile: docker/Dockerfile.keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"

      EXTERNAL_ORIGIN: "${EXTERNAL_ORIGIN:-http://localhost:9080}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    depends_on:
      - postgres

  redis:
    image: redis:7.4
    restart: unless-stopped

  ozmadb:
    build:
      context: .
      dockerfile: docker/Dockerfile.ozmadb
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ozmadb
      DB_PASSWORD: ozmadb
      DB_NAME: ozmadb
      PRELOAD: /etc/ozmadb/preload/preload.json
      EXTERNAL_ORIGIN: ${EXTERNAL_ORIGIN:-http://localhost:9080}
      AUTH_METADATA_ADDRESS: http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      AUTH_REQUIRE_HTTPS_METADATA: "false"
      REDIS: redis
    depends_on:
      - postgres
      - redis
      - keycloak

  ozma-report-generator:
    image: ozmaio/ozma-report-generator:master
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ozma-report-generator
      DB_PASSWORD: ozma-report-generator
      DB_NAME: ozma-report-generator
      AUTH_CLIENT_ID: ozma-report-generator
      EXTERNAL_ORIGIN: ${EXTERNAL_ORIGIN:-http://localhost:9080}
      PATH_BASE: /report-generator
      OZMA_DB_URL: http://ozmadb:5000
      OZMA_DB_FORCE_INSTANCE: ozma
      AUTH_METADATA_ADDRESS: http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      AUTH_REQUIRE_HTTPS_METADATA: "false"
    depends_on:
      - postgres
      - keycloak

  ozma:
    # image: ozmaio/ozma:master
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ozma-localbuild
    restart: unless-stopped
    volumes:
      - caddy_data:/data
    environment:
      ADDRESS: ${CADDY_ADDRESS:-:80}
      KEYCLOAK_HOST: keycloak
      OZMA_DB_HOST: ozmadb
      OZMA_REPORT_GENERATOR_HOST: ozma-report-generator
      TRUSTED_PROXIES: ${DOCKER_SUBNET_GATEWAY}
    ports:
      - ${HTTP_PORT:-9080}:80
        #- ${HTTPS_PORT:-9443}:443
    depends_on:
      - keycloak
      - ozmadb
      - ozma-report-generator

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET_IP}
          gateway: ${DOCKER_SUBNET_GATEWAY}
        
volumes:
  postgres_data:
  caddy_data: