services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    environment:
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: keycloak/keycloak:25.0
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: ${PROTOCOL:-http}://${HOSTNAME:-localhost}:${PORT:-9000}/auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      # Comment these for production
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD:-admin}"
    volumes:
      - ./docker/keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro
    command: ["start", "--import-realm"]
    depends_on:
      - postgres

  ozmadb:
    image: ozmaio/ozmadb:master
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ozmadb
      DB_PASSWORD: ozmadb
      DB_NAME: ozmadb
      PRELOAD: /etc/ozmadb/preload/preload.json
      AUTH_AUTHORITY: ${PROTOCOL:-http}://${HOSTNAME:-localhost}:${PORT:-9000}/auth/realms/ozma
      AUTH_METADATA_ADDRESS: http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      AUTH_REQUIRE_HTTPS_METADATA: false
    volumes:
      - ./ozmadb:/etc/ozmadb/preload:ro
    depends_on:
      - postgres

  ozma:
    image: ozmaio/ozma:master
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - ${PORT:-9000}:80

  ozma-report-generator:
    image: ozmaio/ozma-report-generator:master
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ozma-report-generator
      DB_PASSWORD: ozma-report-generator
      DB_NAME: ozma-report-generator
      AUTH_CLIENT_ID: ozma-report-generator
      ORIGIN: ${PROTOCOL:-http}://${HOSTNAME:-localhost}:${PORT:-9000}
      PATH_BASE: /report-generator
      OZMA_DB_URL: http://ozmadb:5000
      OZMA_DB_FORCE_INSTANCE: ozma
      AUTH_AUTHORITY: ${PROTOCOL:-http}://${HOSTNAME:-localhost}:${PORT:-9000}/auth/realms/ozma
      AUTH_METADATA_ADDRESS: http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      AUTH_REQUIRE_HTTPS_METADATA: false
    depends_on:
      - postgres

volumes:
  postgres_data:
  caddy_data:
