services:
  - name: ozma
    type: web
    runtime: image
    plan: starter
    image:
      url: docker.io/ozmaio/ozma:master
    envVars:
      - key: ADDRESS
        value: http://:10000
      - key: KEYCLOAK_HOST
        fromService:
          name: keycloak
          type: pserv
          property: host
      - key: OZMA_DB_HOST
        fromService:
          name: ozmadb
          type: pserv
          property: host
      - key: OZMA_REPORT_GENERATOR_HOST
        fromService:
          name: ozma-report-generator
          type: pserv
          property: host
      - key: DOMAIN
        sync: false
      # Trust the Render ingress proxy
      - key: TRUSTED_RANGES
        value: 0.0.0.0/0

  - name: keycloak
    type: pserv
    runtime: docker
    plan: standard
    dockerContext: .
    dockerfilePath: docker/Dockerfile.keycloak
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL_HOST
        fromDatabase:
          name: postgres-keycloak
          property: host
      - key: KC_DB_URL_PORT
        fromDatabase:
          name: postgres-keycloak
          property: port
      - key: KC_DB_URL_DATABASE
        fromDatabase:
          name: postgres-keycloak
          property: database
      - key: KC_DB_USERNAME
        fromDatabase:
          name: postgres-keycloak
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: postgres-keycloak
          property: password
      - key: KC_HTTP_RELATIVE_PATH
        value: /auth
      - key: KC_PROXY
        value: edge
      - key: KC_PROXY_HEADERS
        value: xforwarded
      - key: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
        value: "true"
      - key: KC_LOG_LEVEL
        value: info
      - key: KC_METRICS_ENABLED
        value: "true"
      - key: KC_HEALTH_ENABLED
        value: "true"
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        generateValue: true
      - key: EXTERNAL_PROTOCOL
        value: https
      - key: EXTERNAL_HOSTPORT
        fromService:
          name: ozma
          type: web
          envVarKey: DOMAIN
      - key: ADMIN_EMAIL
        sync: false

  - name: ozmadb
    type: pserv
    runtime: docker
    plan: starter
    dockerContext: .
    dockerfilePath: docker/Dockerfile.ozmadb
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres-ozma
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-ozma
          property: port
      - key: DB_USER
        fromDatabase:
          name: postgres-ozma
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-ozma
          property: password
      - key: DB_NAME
        fromDatabase:
          name: postgres-ozma
          property: database
      - key: EXTERNAL_PROTOCOL
        value: https
      - key: EXTERNAL_HOSTPORT
        fromService:
          name: ozma
          type: web
          envVarKey: DOMAIN
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: redis
          property: port

  - name: ozma-report-generator
    type: pserv
    runtime: image
    plan: starter
    image:
      url: docker.io/ozmaio/ozma-report-generator:master
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres-ozma-report-generator
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-ozma-report-generator
          property: port
      - key: DB_USER
        fromDatabase:
          name: postgres-ozma-report-generator
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-ozma-report-generator
          property: password
      - key: DB_NAME
        fromDatabase:
          name: postgres-ozma-report-generator
          property: database
      - key: AUTH_CLIENT_ID
        value: ozma-report-generator
      - key: PATH_BASE
        value: /report-generator
      - key: OZMA_DB_HOST
        fromService:
          name: ozmadb
          type: pserv
          property: host
      - key: OZMA_DB_FORCE_INSTANCE
        value: ozma
      - key: EXTERNAL_PROTOCOL
        value: https
      - key: EXTERNAL_HOSTPORT
        fromService:
          name: ozma
          type: web
          envVarKey: DOMAIN

  - name: redis
    type: redis
    plan: free
    ipAllowList: []
databases:
  - name: postgres-ozma
    plan: basic-256mb
    ipAllowList: []
  - name: postgres-keycloak
    plan: basic-256mb
    ipAllowList: []
  - name: postgres-ozma-report-generator
    plan: basic-256mb
    ipAllowList: []
