FROM node:20 AS build
WORKDIR /app
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
RUN corepack enable && yarn install
COPY . .
RUN yarn build

FROM caddy
RUN setcap -r /usr/bin/caddy
COPY --from=build /app/dist /usr/share/caddy
COPY ./docker/Caddyfile.ozma /etc/caddy/Caddyfile