# Build stage
FROM node:20-alpine AS build
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock .yarnrc.yml .pnp.cjs .pnp.loader.mjs ./
COPY .yarn .yarn
RUN yarn install --immutable

# Copy source and build
COPY . .
RUN yarn build

# Final stage
FROM caddy
# https://kofi.sexy/blog/zero-downtime-render-disk
RUN setcap -r /usr/bin/caddy
COPY --from=build /app/dist /usr/share/caddy
COPY docker/Caddyfile.ozma /etc/caddy/Caddyfile
